In [ ]:
import pandas as pd
import numpy as np

#Loading Data

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/chipotle.tsv",sep='\t')

In [ ]:
df

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]     $3.39   
2                                               [Apple]     $3.39   
3                                                   NaN     $2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


In [ ]:
df.shape

(4622, 5)

In [ ]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

1. **Missing Values:**

Question: Check for missing values in each column (Order ID, Quantity, Item Name, Choice Description, Item Price). How should missing values be handled?

In [ ]:
df.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:
df.choice_description = df.choice_description.fillna("No choice")

In [ ]:
df.choice_description.head()

0                                            No choice
1                                         [Clementine]
2                                              [Apple]
3                                            No choice
4    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
Name: choice_description, dtype: object

**2. Data Types:**

Question: Verify the data types of each column. Do they align with their expected types, and should any adjustments be made?

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  4622 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


Here item_price data type shouldn't be object, it should replace with **int or float ** insted of object

In [ ]:
df.item_price.head(10)

0     $2.39 
1     $3.39 
2     $3.39 
3     $2.39 
4    $16.98 
5    $10.98 
6     $1.69 
7    $11.75 
8     $9.25 
9     $9.25 
Name: item_price, dtype: object

As we see the above data, each item is of **float** type

In [ ]:
df["item_price"] = df["item_price"].apply(lambda x : x.replace("$",''))

In [ ]:
df["item_price"].head()

0     2.39 
1     3.39 
2     3.39 
3     2.39 
4    16.98 
Name: item_price, dtype: object

In [ ]:
df["item_price"] = df["item_price"].astype(float)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   order_id            4622 non-null   int64  
 1   quantity            4622 non-null   int64  
 2   item_name           4622 non-null   object 
 3   choice_description  4622 non-null   object 
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB


**3.Duplicated Entries:**

Question: Identify and handle duplicated entries in the dataset. How might duplicates impact analysis, and what is the appropriate action?

In [ ]:
df.duplicated().value_counts()

False    4563
True       59
dtype: int64

There are 59 duplicate rows

In [ ]:
d = df[df.duplicated()]

In [ ]:
df.drop_duplicates(keep='first', inplace=True)

In [ ]:
df.duplicated().sum()

0

4. **Quantity and Item Price:**


Question: Examine the Quantity and Item Price columns. Are there any inconsistencies or anomalies that need correction?

In [ ]:
print(df["quantity"].value_counts())
df["quantity"].unique()

1     4296
2      224
3       28
4       10
5        1
15       1
7        1
8        1
10       1
Name: quantity, dtype: int64


array([ 1,  2,  3,  4,  5, 15,  7,  8, 10])

Here the quantities are ranging from 1 to 5 and compared to other quantities there is a huge difference between them so we consider them as **Outliers**

In [ ]:
condition = (df['quantity'] > 7)
df.drop(df[condition].index, inplace=True) #outliers are removed

In [ ]:
print(df["quantity"].value_counts())
df["quantity"].unique()

1    4296
2     224
3      28
4      10
5       1
7       1
Name: quantity, dtype: int64


array([1, 2, 3, 4, 5, 7])

In [ ]:
print(df["item_price"].value_counts())
df["item_price"].unique()

8.75     719
11.25    516
9.25     395
4.45     344
8.49     308
        ... 
6.45       1
13.35      1
7.50       1
4.36       1
11.49      1
Name: item_price, Length: 75, dtype: int64


array([ 2.39,  3.39, 16.98, 10.98,  1.69, 11.75,  9.25,  4.45,  8.75,
       11.25,  8.49,  2.18,  8.99,  1.09,  2.95,  2.15,  3.99, 22.5 ,
       11.48, 17.98, 17.5 ,  4.3 ,  5.9 ,  1.25, 23.78,  6.49, 11.08,
        1.5 , 22.16, 32.94, 22.2 , 10.58,  2.5 , 23.5 ,  7.4 , 18.5 ,
        3.  ,  6.78, 11.89,  9.39,  4.  ,  3.75,  8.69,  2.29,  8.9 ,
        3.27,  3.89,  8.19, 35.  , 27.75, 11.8 ,  6.  , 26.25, 21.96,
        4.36,  7.5 ,  4.78, 13.35,  6.45,  5.07, 22.96,  7.17,  7.98,
        4.5 , 26.07, 12.98, 35.25, 10.5 , 33.75, 16.38,  5.  ,  8.5 ,
       17.8 ,  1.99, 11.49])

In [ ]:
df['item_price'] <= 0

0       False
1       False
2       False
3       False
4       False
        ...  
4617    False
4618    False
4619    False
4620    False
4621    False
Name: item_price, Length: 4560, dtype: bool

4.Choice Description:


Question: Analyze the Choice Description column. How should choices be handled, especially when there are multiple descriptions for a single item?

In [ ]:
df["choice_description"].unique()

array(['No choice', '[Clementine]', '[Apple]', ...,
       '[Roasted Chili Corn Salsa, [Pinto Beans, Sour Cream, Cheese, Lettuce, Guacamole]]',
       '[Tomatillo Green Chili Salsa, [Rice, Black Beans]]',
       '[Tomatillo Green Chili Salsa, [Rice, Fajita Vegetables, Black Beans, Guacamole]]'],
      dtype=object)

In [ ]:
df["choice_description"]=df["choice_description"].str.replace("[","").str.replace("]","")

<ipython-input-50-87543edc9ee9>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["choice_description"]=df["choice_description"].str.replace("[","").str.replace("]","")


In [ ]:
df["choice_description"].unique()

array(['No choice', 'Clementine', 'Apple', ...,
       'Roasted Chili Corn Salsa, Pinto Beans, Sour Cream, Cheese, Lettuce, Guacamole',
       'Tomatillo Green Chili Salsa, Rice, Black Beans',
       'Tomatillo Green Chili Salsa, Rice, Fajita Vegetables, Black Beans, Guacamole'],
      dtype=object)

In [ ]:
df["choice_description"] = df["choice_description"].str.lower()

In [ ]:
df.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  
0                                          no choice        2.39  
1                                         clementine        3.39  
2                                              apple        3.39  
3                                          no choice        2.39  
4  tomatillo-red chili salsa (hot), black beans, ...       16.98

6. Handling Special Characters:

Question: Check for special characters in text-based columns (e.g., Item Name, Choice Description). How can these be addressed for consistency?

In [ ]:
df["item_name"] = df["item_name"].replace("-"," ",regex=True)

In [ ]:
df["item_name"] = df["item_name"].str.lower()

In [ ]:
df["item_name"].unique()

array(['chips and fresh tomato salsa', 'izze', 'nantucket nectar',
       'chips and tomatillo green chili salsa', 'chicken bowl',
       'side of chips', 'steak burrito', 'steak soft tacos',
       'chips and guacamole', 'chicken crispy tacos',
       'chicken soft tacos', 'chicken burrito', 'canned soda',
       'barbacoa burrito', 'carnitas burrito', 'carnitas bowl',
       'bottled water', 'barbacoa bowl', 'chips', 'chicken salad bowl',
       'steak bowl', 'barbacoa soft tacos', 'veggie burrito',
       'veggie bowl', 'steak crispy tacos',
       'chips and tomatillo red chili salsa', 'barbacoa crispy tacos',
       'veggie salad bowl', 'chips and roasted chili corn salsa',
       'carnitas soft tacos', 'chicken salad', 'canned soft drink',
       'steak salad bowl', '6 pack soft drink', 'bowl', 'burrito',
       'crispy tacos', 'carnitas crispy tacos', 'steak salad',
       'chips and mild fresh tomato salsa', 'veggie soft tacos',
       'carnitas salad bowl', 'barbacoa salad bow

In [ ]:
df["choice_description"] = df["choice_description"].replace("-"," ",regex=True)

In [ ]:
df["choice_description"].unique()

array(['no choice', 'clementine', 'apple', ...,
       'roasted chili corn salsa, pinto beans, sour cream, cheese, lettuce, guacamole',
       'tomatillo green chili salsa, rice, black beans',
       'tomatillo green chili salsa, rice, fajita vegetables, black beans, guacamole'],
      dtype=object)

7.Order Id Integrity:


Question: Cross-reference the Order ID column for integrity. Are there any irregularities or patterns that need validation?

In [ ]:
df['order_id'].unique()

array([   1,    2,    3, ..., 1832, 1833, 1834])

In [ ]:
df['order_id'].isnull().any()

False

In [ ]:
df['order_id'].dtype

dtype('int64')

Item Name Standardization:

Question: Standardize the Item Name column. Are there variations that can be unified for better analysis?

In [ ]:
df["item_name"] = df["item_name"].str.strip()

In [ ]:
df["item_name"].head()

0             chips and fresh tomato salsa
1                                     izze
2                         nantucket nectar
3    chips and tomatillo green chili salsa
4                             chicken bowl
Name: item_name, dtype: object

Data Integrity Check:

Question: Perform a data integrity check by ensuring that quantities and prices align with the corresponding items and descriptions.

In [ ]:
grouped_data = df.groupby(['item_name', 'choice_description']).agg({
    'quantity': 'sum',
    'item_price': lambda x: x.astype(float).mean()
}).reset_index()

In [ ]:
grouped_data

item_name                                 choice_description  \
0     6 pack soft drink                                               coke   
1     6 pack soft drink                                          diet coke   
2     6 pack soft drink                                           lemonade   
3     6 pack soft drink                                             nestea   
4     6 pack soft drink                                             sprite   
...                 ...                                                ...   
1863  veggie soft tacos  fresh tomato salsa, black beans, cheese, sour ...   
1864  veggie soft tacos  fresh tomato salsa, fajita vegetables, rice, b...   
1865  veggie soft tacos  roasted chili corn salsa (medium), black beans...   
1866  veggie soft tacos  roasted chili corn salsa, fajita vegetables, b...   
1867  veggie soft tacos  tomatillo red chili salsa, fajita vegetables, ...   

      quantity  item_price  
0           21    6.490000  
1           25    6.760417  
2            2    6.490000  
3            2    6.490000  
4            5    6.490000  
...        ...         ...  
1863         1    8.750000  
1864         1   11.250000  
1865         1    8.490000  
1866         1    8.750000  
1867         1   11.250000  

[1868 rows x 4 columns]

#1. Quantity of each item?

In [ ]:
total_quantity_per_item = df.groupby('item_name')['quantity'].sum().reset_index()

In [ ]:
total_quantity_per_item

item_name  quantity
0                       6 pack soft drink        55
1                           barbacoa bowl        65
2                        barbacoa burrito        90
3                   barbacoa crispy tacos        12
4                     barbacoa salad bowl         9
5                     barbacoa soft tacos        25
6                           bottled water       194
7                                    bowl         4
8                                 burrito         6
9                             canned soda       124
10                      canned soft drink       340
11                          carnitas bowl        71
12                       carnitas burrito        60
13                  carnitas crispy tacos         8
14                         carnitas salad         1
15                    carnitas salad bowl         6
16                    carnitas soft tacos        40
17                           chicken bowl       752
18                        chicken burrito       584
19                   chicken crispy tacos        50
20                          chicken salad         9
21                     chicken salad bowl       123
22                     chicken soft tacos       116
23                                  chips       227
24           chips and fresh tomato salsa       115
25                    chips and guacamole       501
26      chips and mild fresh tomato salsa         1
27     chips and roasted chili corn salsa        41
28  chips and tomatillo green chili salsa        78
29    chips and tomatillo red chili salsa        72
30                           crispy tacos         2
31                                   izze        19
32                       nantucket nectar        29
33                                  salad         2
34                          side of chips       102
35                             steak bowl       220
36                          steak burrito       383
37                     steak crispy tacos        36
38                            steak salad         4
39                       steak salad bowl        31
40                       steak soft tacos        56
41                            veggie bowl        87
42                         veggie burrito        97
43                    veggie crispy tacos         1
44                           veggie salad         6
45                      veggie salad bowl        18
46                      veggie soft tacos         8

#2.	What was the most ordered item in the choice_description column?

In [ ]:
choice_counts = df['choice_description'].value_counts()
most_ordered_item = choice_counts.idxmax()
most_ordered_count = choice_counts.max()

In [ ]:
choice_counts

no choice                                                                                                                                  1225
diet coke                                                                                                                                   133
coke                                                                                                                                        115
sprite                                                                                                                                       77
fresh tomato salsa, rice, black beans, cheese, sour cream, lettuce                                                                           41
                                                                                                                                           ... 
tomatillo green chili salsa, sour cream, cheese, guacamole, rice, fajita vegetables                                                     

In [ ]:
most_ordered_count

1225

In [ ]:
most_ordered_item

'no choice'

#3. How many items were ordered in total?

In [ ]:
total_items_ordered = df['quantity'].sum()
total_items_ordered

4880

#4.	How much was the revenue for the period in the dataset?

In [ ]:
df['revenue'] = df['quantity'] * df['item_price']
total_revenue = df['revenue'].sum() # Calculate the total revenue for the period

In [ ]:
total_revenue

37992.200000000004

In [ ]:
df.head()

order_id  quantity                              item_name  \
0         1         1           chips and fresh tomato salsa   
1         1         1                                   izze   
2         1         1                       nantucket nectar   
3         1         1  chips and tomatillo green chili salsa   
4         2         2                           chicken bowl   

                                  choice_description  item_price  revenue  
0                                          no choice        2.39     2.39  
1                                         clementine        3.39     3.39  
2                                              apple        3.39     3.39  
3                                          no choice        2.39     2.39  
4  tomatillo red chili salsa (hot), black beans, ...       16.98    33.96

#5.	How many orders were made in the period?

In [ ]:
total_orders = df['order_id'].nunique()

In [ ]:
total_orders

1834

#6.	What is the average revenue amount per order?

In [ ]:
avg_revenue_per_order = total_revenue / total_orders

In [ ]:
avg_revenue_per_order

20.7154852780807

#7.	How many different items are sold?

In [ ]:
df['item_name'].nunique()

47